[ASPECT]

[ASPECT.cartesian_3D_nproc4]
archive_path = "data/aspect/output_convection_box_3d"
archive_ext = ".tar.gz"
relative_unpacked_path = "nproc_4/solution"
sample_file = "solution-00002.pvtu"
info = "mpirun with 4 procs, ASPECT cookbook, multiple timesteps"

[ASPECT.cartesian_3D_nproc1]
archive_path = "data/aspect/output_convection_box_3d"
archive_ext = ".tar.gz"
relative_unpacked_path = "nproc_1/solution"
sample_file = "solution-00002.pvtu"
info = "single processor ASPECT cookbook, multiple timesteps"

[PVTU]

[PVTU.cleaned_aspect]
archive_path = "data/pvtu/aspect_cleaned_output_convection_box_nproc4"
archive_ext = ".tar.gz"
relative_unpacked_path = "solution"
sample_file = "solution-00003.pvtu"
info = "cleaned version of ASPECT run that should be identified as a general PVTU not ASPECT"

