name: Style Checks
on: [pull_request]

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: install
      id: install
      run : pip install -r tests/lint_requirements.txt

    - name: check
      id: flake8
      run: |
        flake8 --version
        flake8 yt_aspect/
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: install
      id: install
      run : pip install -r tests/lint_requirements.txt

    - name: check
      id: black
      run: |
        black --version
        black --check --diff yt_aspect/
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: install
      id: install
      run : pip install -r tests/lint_requirements.txt

    - name: check
      id: isort
      run: |
        isort --version-number
        isort . --check --diff